language: python
notifications:
  email: false
python:
  - 2.7
install:
  - pip install -r full_requirements.txt
script:
  - python -m unittest discover -v -s tests/
  - cd docs/
  - make html
  - python snippets/test_tutorial_sample.py
